### PR TITLE
Decrease Jersey autodiscoverable level

### PR DESCRIPTION
**Pull request by jordillonch**
Current `Jersey` autodiscoverable priority is high than default. This can cause `Genson` becomes default serializer for `Jersey` in projects that are using other serializers when you add `Genson` or some custom library that has `Genson` as dependency.
This PR tries to solve this issue.

### CODE REVIEW

**Comment by EugenCepoi** [comment]
Thank you for opening this PR!

Genson can be [disabled from jersey](http://owlike.github.io/genson/Documentation/Extensions/#jax-rs-jersey--cie). With something like this: `new ResourceConfig().register(new GensonJaxRSFeature().disable());`.

If a project is using another serializer, then it means that this serailizer must have a higher priority than Genson right (so Genson is not picked)? But then, what about the other case around, where someone is using Genson and relies on it to be used instead of say Moxy? My point is that I am not sure this priority thing in general works as everyone has different needs.

What do you think? Does it sound like a good enough solution to disable Genson rather than relying on some hardcoded order?

**Comment by jordillonch** [comment]
It should not be a discussion about who should have more priority. I think if you are using a priority higher than default there are more chances to create some issues when Genson is added as a dependency in a project. 

My point is that any library should take care to be less disrupting as posible and when you are using autodiscovering magic you are in the way to generate not desired side effects.
I do not believe that the solution is to increase other serializer priority or disable genson, I think you must explicit what serializer want to use in your project but in my case I have a problem with a big legacy code that it will be broken if I include Genson dependency.

I agree that there is a problem with that legacy code but I also think that is not good that Genson could broke any code because that magic. 😄

**Comment by EugenCepoi** [comment]
If we look at [Moxy](https://github.com/jersey/jersey/blob/master/media/moxy/src/main/java/org/glassfish/jersey/moxy/json/internal/MoxyJsonAutoDiscoverable.java#L55) we can see that they have the same priority as Genson. Increasing the priority of Genson would just disable it wherever people have Moxy. Moxy comes often bundled with glassfish, while Genson must be added explicitly - and in most cases is intended to be used as the project json ser/de instead of whatever else is there.

I am not very enthusiastic in changing the priority because:
 - We agree that the priority is a stupid way to hint jersey what module to pick.
 - There is a way to explicitly say disable Genson, but also there are ways to explicitly say what lib to use (independent of the priority), this is true for old versions of jersey too. Even if this project is "big legacy" you very likely have a way to configure it.
 - This change might break the system for other users in subtle ways, while you already know where the problem would be and can address it without breaking things.

Also why do you want to have both libs at the same time?

**Comment by jordillonch** [comment]
Well, I don't think that because Moxy is using some priority Genson can no be less. I'm still thinking that both project should use a priority less than default.
My points are:
- A library should avoid any side effect when is added to a project.
- Disabling Genson sound to me as a patch. I agree that a project must explicit a serializer to use but it could be complex when you have a big legacy project with Spring, Liferay and lots of magic.
- Change the priority on next release is not breaking anything if you release a major version and explain the issue about the priority.

About to have both libs, we created a new library that will be used to some different projects in order to split this legacy code. I don't think that the library should take into account what kind of serializer is used for every project. The library comes with one that is the best choice for the purposes of the library.

**Comment by EugenCepoi** [comment]
I initially chose to use the same priority as Moxy so when they are both
present, Moxy isn't being picked over Genson. This worked well overall.

> "The library comes with one that is the best choice for the purposes of
the library"

Then it shouldn't rely on any magical auto discovery and just register the
serializer the lib wants to use.

I still feel that this change would work well for your specific scenario
without being good for what most people expect (when they add Genson to
have it magically work). An example of how it gets cumbersome for someone
to use another lib instead of Moxy when it comes with the web server:

http://stackoverflow.com/questions/39881226/messagebodywriter-not-found-for-media-type-application-json-with-gf4-and-jackson
https://kunalransing.wordpress.com/2015/03/24/glassfish-4-1-replace-default-moxy-json-binding-provider-by-jackson-2-5-1/

Please try disabling Genson or explicitly registering the serializer lib
you want to use.

2016-10-06 0:40 GMT-07:00 Jordi Llonch <notifications@github.com>:

**Comment by jordillonch** [comment]
I know current solution is only to disable Genson. It's just that it sounds very strange to me that it could happen when I add a third party library my project can be broken because the autodiscovery mechanism. Also that the solution is to disable the library. It sounds like a patch and is when I start thinking that something is wrong.
To say that other library is doing the same doesn't convince me.
Anyway, thanks for this healthy discussion 😄

**Pull request closed without merging**
